# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Break me
#' @param msg
#' @export
rcpp_break <- function(msg) {
    invisible(.Call(`_vscodeRcppPkg_rcpp_break`, msg))
}

rcpp_any <- function(expr) {
    invisible(.Call(`_vscodeRcppPkg_rcpp_any`, expr))
}

#' Simple sum
#' @param x a numeric vector
#' @export
rcpp_sum <- function(x) {
    .Call(`_vscodeRcppPkg_rcpp_sum`, x)
}

#' Simple mean
#' @param x a numeric vector
#' @export
rcpp_mean <- function(x) {
    .Call(`_vscodeRcppPkg_rcpp_mean`, x)
}

#' Concats two vectors
#' @param a first numeric vector
#' @param b second numeric vector
#' @export
rcpp_concat <- function(a, b) {
    .Call(`_vscodeRcppPkg_rcpp_concat`, a, b)
}

#' Returns x[idx]
#' @param x a numeric vector
#' @param idx the index
#' @export
rcpp_idx <- function(x, idx) {
    .Call(`_vscodeRcppPkg_rcpp_idx`, x, idx)
}

