# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tbb_arena_parallelVectorSum <- function(x) {
    .Call(`_RcppParallelNumThreads_tbb_arena_parallelVectorSum`, x)
}

tbb_global_control_parallelVectorSum <- function(x) {
    .Call(`_RcppParallelNumThreads_tbb_global_control_parallelVectorSum`, x)
}

tbb_parallel_sleep <- function(N, ms) {
    invisible(.Call(`_RcppParallelNumThreads_tbb_parallel_sleep`, N, ms))
}

parallelVectorSum <- function(x) {
    .Call(`_RcppParallelNumThreads_parallelVectorSum`, x)
}

